name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run semantic-release
        run: npm run release
        env:
          GITHUB_TOKEN: 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
